[workspace]
resolver = "2"
members = [
    "crates/scry-core",
    "crates/scry-proto",
    "crates/scry-plugin-sdk",
    "crates/scry-weather-plugin",
    "crates/scry-spotify-plugin",
    "crates/scry-github-plugin",
]

[workspace.package]
# x-release-please-start-version
version = "0.2.0"
# x-release-please-end

