// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiEntity = { namespace: string, typ: string, id: string, title: string, photo_url: string | null, link: string, };
