// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiReportMetadata = { id: string, name: string, description: string, viz: string, };
