// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiWidgetTemplate } from "./ApiWidgetTemplate";

export type ApiWidgetDefinition = { id: string, title: string, template: ApiWidgetTemplate, config_json: string, };
