// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CorrelateParams = { base_category: string | null, join_category: string | null, base_semantic: string | null, join_semantic: string | null, limit: number | null, };
