// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type DashboardWidget = { id: string, dashboard_id: string, type: string, title: string | null, config: JsonValue, width_span: number, sort_order: number, };
