// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardWidget } from "./DashboardWidget";

export type Dashboard = { id: string, name: string, slug: string, is_default: boolean, widgets: Array<DashboardWidget>, };
