// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type Event = { id: string, timestamp: string, category: string, source: string, payload: JsonValue, metadata: JsonValue | null, entities: Array<EntityRef>, context: Array<string>, context_info: JsonValue | null, display_title: string | null, display_subtitle: string | null, };
