// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiDataField } from "./ApiDataField";
import type { ApiReportMetadata } from "./ApiReportMetadata";
import type { ApiTraitCapability } from "./ApiTraitCapability";
import type { ApiWidgetDefinition } from "./ApiWidgetDefinition";

export type PluginStatus = { id: string, name: string, version: string, description: string, roles: Array<string>, capabilities: Array<string>, subscriptions: Array<string>, exports: Array<ApiDataField>, provided_traits: Array<ApiTraitCapability>, reports: Array<ApiReportMetadata>, config_schema: string | null, suggested_widgets: Array<ApiWidgetDefinition>, };
