// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiReportMetadata } from "./ApiReportMetadata";

export type PluginReports = { plugin: string, reports: Array<ApiReportMetadata>, };
